apiVersion: apps/v1
kind: Deployment
metadata:
  name: owlban-backend
  labels:
    app: owlban-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owlban-backend
  template:
    metadata:
      labels:
        app: owlban-backend
    spec:
      containers:
      - name: flask-backend
        image: owlban/flask-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: OSCAR_BROOME_URL
          value: "http://owlban-node:4000"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: owlban-secrets
              key: jwt-secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: owlban-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      - name: node-backend
        image: owlban/node-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: owlban-backend-service
spec:
  selector:
    app: owlban-backend
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
  - name: node
    port: 4000
    targetPort: 4000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: owlban-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - owlban.example.com
    secretName: owlban-tls
  rules:
  - host: owlban.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: owlban-backend-service
            port:
              number: 5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: owlban-config
data:
  FLASK_ENV: "production"
  NODE_ENV: "production"
  LOG_LEVEL: "INFO"

---
apiVersion: v1
kind: Secret
metadata:
  name: owlban-secrets
type: Opaque
data:
  jwt-secret: <base64-encoded-jwt-secret>
  database-url: <base64-encoded-database-url>
  jpmorgan-api-key: <base64-encoded-api-key>

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: owlban-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: owlban-backend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: owlban-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: owlban-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
